// <auto-generated />
using System;
using Human_resources_managment.PostgresDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Human_resources_managment.Migrations
{
    [DbContext(typeof(DBContextHRM))]
    [Migration("20251217095812_FixRelationsToOneToMany")]
    partial class FixRelationsToOneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Departments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            Description = "Технический отдел, отвечающий за все компьютеры в офисе"
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            Description = "Бухгалтерский отдел, отвечающий за деньги"
                        },
                        new
                        {
                            Id = new Guid("cccc3333-3333-3333-3333-333333333333"),
                            Description = "Испытательный центр, испытывает все нововедения"
                        });
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Employees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeee4444-4444-4444-4444-444444444444"),
                            DepartmentId = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            PositionId = new Guid("33222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("ffff5555-5555-5555-5555-555555555555"),
                            DepartmentId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            PositionId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("dddd6666-6666-6666-6666-666666666666"),
                            DepartmentId = new Guid("cccc3333-3333-3333-3333-333333333333"),
                            PositionId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Positions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("33222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Departments", b =>
                {
                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.NameVO", "Name", b1 =>
                        {
                            b1.Property<Guid>("DepartmentsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("name");

                            b1.HasKey("DepartmentsId");

                            b1.ToTable("departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentsId");

                            b1.HasData(
                                new
                                {
                                    DepartmentsId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                                    Name = "IT"
                                },
                                new
                                {
                                    DepartmentsId = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                                    Name = "Бухгалтерский"
                                },
                                new
                                {
                                    DepartmentsId = new Guid("cccc3333-3333-3333-3333-333333333333"),
                                    Name = "ИЦ"
                                });
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Employees", b =>
                {
                    b.HasOne("Human_resources_managment.Models.DataBaseModels.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Human_resources_managment.Models.DataBaseModels.Positions", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.DateVO", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");

                            b1.HasData(
                                new
                                {
                                    EmployeesId = new Guid("eeee4444-4444-4444-4444-444444444444"),
                                    Date = new DateOnly(2004, 4, 22)
                                },
                                new
                                {
                                    EmployeesId = new Guid("ffff5555-5555-5555-5555-555555555555"),
                                    Date = new DateOnly(2000, 12, 1)
                                },
                                new
                                {
                                    EmployeesId = new Guid("dddd6666-6666-6666-6666-666666666666"),
                                    Date = new DateOnly(1980, 8, 15)
                                });
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.DateVO", "HireDate", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("hire_date");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");

                            b1.HasData(
                                new
                                {
                                    EmployeesId = new Guid("eeee4444-4444-4444-4444-444444444444"),
                                    Date = new DateOnly(2025, 4, 22)
                                },
                                new
                                {
                                    EmployeesId = new Guid("ffff5555-5555-5555-5555-555555555555"),
                                    Date = new DateOnly(2024, 4, 22)
                                },
                                new
                                {
                                    EmployeesId = new Guid("dddd6666-6666-6666-6666-666666666666"),
                                    Date = new DateOnly(2000, 1, 1)
                                });
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObject.PhoneVO", "Phone", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");

                            b1.HasData(
                                new
                                {
                                    EmployeesId = new Guid("eeee4444-4444-4444-4444-444444444444"),
                                    Phone = "+79999999999"
                                },
                                new
                                {
                                    EmployeesId = new Guid("ffff5555-5555-5555-5555-555555555555"),
                                    Phone = "+79889999966"
                                },
                                new
                                {
                                    EmployeesId = new Guid("dddd6666-6666-6666-6666-666666666666"),
                                    Phone = "+79779999933"
                                });
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.EmailVO", "Email", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");

                            b1.HasData(
                                new
                                {
                                    EmployeesId = new Guid("eeee4444-4444-4444-4444-444444444444"),
                                    Email = "amail@mail.ru"
                                },
                                new
                                {
                                    EmployeesId = new Guid("ffff5555-5555-5555-5555-555555555555"),
                                    Email = "pamail@mail.ru"
                                },
                                new
                                {
                                    EmployeesId = new Guid("dddd6666-6666-6666-6666-666666666666"),
                                    Email = "mamail@mail.ru"
                                });
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.FullNameVO", "FullName", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MidleName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("middle_name");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");

                            b1.HasData(
                                new
                                {
                                    EmployeesId = new Guid("eeee4444-4444-4444-4444-444444444444"),
                                    FirstName = "Абдула",
                                    LastName = "Али"
                                },
                                new
                                {
                                    EmployeesId = new Guid("ffff5555-5555-5555-5555-555555555555"),
                                    FirstName = "Резников",
                                    LastName = "Константин",
                                    MidleName = "Игоревич"
                                },
                                new
                                {
                                    EmployeesId = new Guid("dddd6666-6666-6666-6666-666666666666"),
                                    FirstName = "Игнатьев",
                                    LastName = "Валентайн",
                                    MidleName = "Архипович"
                                });
                        });

                    b.Navigation("BirthDate")
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("HireDate")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Positions", b =>
                {
                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.NameVO", "Name", b1 =>
                        {
                            b1.Property<Guid>("PositionsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("name");

                            b1.HasKey("PositionsId");

                            b1.ToTable("positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionsId");

                            b1.HasData(
                                new
                                {
                                    PositionsId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    Name = "Инженер"
                                },
                                new
                                {
                                    PositionsId = new Guid("22222222-2222-2222-2222-222222222222"),
                                    Name = "Инженер-программист"
                                },
                                new
                                {
                                    PositionsId = new Guid("33222222-2222-2222-2222-222222222222"),
                                    Name = "Бухгалтер"
                                });
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
