// <auto-generated />
using System;
using Human_resources_managment.PostgresDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Human_resources_managment.Migrations
{
    [DbContext(typeof(DBContextHRM))]
    [Migration("20251216114514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Departments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Employees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Positions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Departments", b =>
                {
                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.NameVO", "Name", b1 =>
                        {
                            b1.Property<Guid>("DepartmentsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("name");

                            b1.HasKey("DepartmentsId");

                            b1.ToTable("departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentsId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Employees", b =>
                {
                    b.HasOne("Human_resources_managment.Models.DataBaseModels.Departments", "Department")
                        .WithOne("Employee")
                        .HasForeignKey("Human_resources_managment.Models.DataBaseModels.Employees", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Human_resources_managment.Models.DataBaseModels.Positions", "Position")
                        .WithOne("Employee")
                        .HasForeignKey("Human_resources_managment.Models.DataBaseModels.Employees", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.DateVO", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.DateVO", "HireDate", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("hire_date");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObject.PhoneVO", "Phone", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.EmailVO", "Email", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");
                        });

                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.FullNameVO", "FullName", b1 =>
                        {
                            b1.Property<Guid>("EmployeesId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MidleName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("middle_name");

                            b1.HasKey("EmployeesId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeesId");
                        });

                    b.Navigation("BirthDate")
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("HireDate")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Positions", b =>
                {
                    b.OwnsOne("Human_resources_managment.Models.ValueObjectModels.NameVO", "Name", b1 =>
                        {
                            b1.Property<Guid>("PositionsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("name");

                            b1.HasKey("PositionsId");

                            b1.ToTable("positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionsId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Departments", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Human_resources_managment.Models.DataBaseModels.Positions", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
